#version: "3.9"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    container_name: plex
    network_mode: host
#    ports:
     # - 32400:32400/tcp
     # - 3005:3005/tcp
     # - 8324:8324/tcp
     # - 32469:32469/tcp
     # - 1900:1900/udp
     # - 32410:32410/udp
     # - 32412:32412/udp
     # - 32413:32413/udp
     # - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - VERSION=docker
      - PLEX_CLAIM=claim-MReAGi92dYEhcxirx6Vn
    volumes:
      - /home/library/media/library:/config
      - /home/library/media/shows:/tv
      - /home/library/media/movies:/movies

  torrserver:
    image: ghcr.io/yourok/torrserver
    container_name: torrserver
    network_mode: host    # to allow DLNA feature
    environment:
      - TS_PORT=8090
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
    volumes:
      - /home/library/torrserver/torrents:/opt/ts/torrents
      - /home/library/torrserver/config:/opt/ts/config
    ports:
      - 8090:8090
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - TRANSMISSION_WEB_HOME= #optional
      # - USER= #optional
      # - PASS= #optional
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    volumes:
      - ./transmission/config:/config
      - /home/library/media/movies:/movies
      - /home/library/media/shows:/shows
      - /home/library/media/torrent:/torrent
      # - /home/library/movies/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  db:
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  app:
    hostname: nextcloud.cool-family.keenetic.link
    image: nextcloud
    restart: always
    ports:
      - 15880:80
      - 15443:443
    volumes:
      - nextcloud:/var/www/html
      - /home/library/photo_library:/var/www/html/data
      - /home/library/HomeLibrary/nextcloud/config:/var/www/html/config
    environment:
 #     - NEXTCLOUD_HOSTNAME=localhost
      - POSTGRES_HOST=db
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user

volumes:
  nextcloud:

secrets:
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  nextcloud_admin_password:
    file: ./secrets/nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: ./secrets/nextcloud_admin_user.txt

networks:
    external:
      name: keenetic-net