version: "3.9"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - VERSION=docker
      - PLEX_CLAIM=my_claim
    volumes:
      - /home/library/movies/library:/config
      - /home/library/movies/shows:/tv
      - /home/library/movies/movies:/movies

  nextcloud_db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - secret.env

  redis:
    image: redis:alpine
    restart: always

  nextcloud_web:
    image: nextcloud:apache
    restart: always
    ports:
      - 15880:80
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      # - VIRTUAL_HOST=cloud.yourdomain.com
      # - LETSENCRYPT_HOST=cloud.yourdomain.com
      # - LETSENCRYPT_EMAIL=yourmail # <===== For let's encrypt
      - POSTGRES_HOST=nextcloud_db
      - REDIS_HOST=redis
    env_file:
      - secret.env
    depends_on:
      - nextcloud_db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud_db
      - redis

networks:
  default:
    external:
      name: keenetic-net

# volumes:
#   nextcloud_dbdata:
#   nextcloud:

  # db_nextcloud:
  #   image: postgres:latest
  #   hostname: db_nextcloud
  #   container_name: nextcloud-postgres
  #   networks:
  #     - nextcloud_network
  #   restart: unless-stopped
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./postgres:/var/lib/postgresql/data:rw
  #     - /etc/localtime:/etc/localtime:ro
  #   # env_file: .secret
  #   environment:
  #     - POSTGRES_DB=testdb
  #     - POSTGRES_USER=testuser
  #     - POSTGRES_PASSWORD=4Xxg&r2LJJiTwRRrr
    # secrets:
    #   - postgres_db
    #   - postgres_password
    #   - postgres_user
    # labels:
    #   - traefik.enable=false

  # nextcloud:
  #   image: nextcloud:latest
  #   container_name: nextcloud
  #   networks:
  #     - nextcloud_network
  #   restart: unless-stopped
  #   ports:
  #     - 15880:80
  #   volumes:
  #     - ./nextcloud:/var/www/html
  #     - ./nextcloud/config:/var/www/html/config
  #     # - ./nextcloud/custom_apps:/var/www/html/custom_apps
  #     - ./nextcloud/data:/var/www/html/data
  #     # - ./nextcloud/themes:/var/www/html/themes
  #     - /etc/localtime:/etc/localtime:ro
  #   # env_file: .secret
  #   environment:
  #     - POSTGRES_HOST=db_nextcloud
  #     - POSTGRES_DB=testdb
  #     - POSTGRES_USER=testuser
  #     - POSTGRES_PASSWORD=4Xxg&r2LJJiTwRRrr
  #     - NEXTCLOUD_ADMIN_PASSWORD=admpass
  #     - NEXTCLOUD_ADMIN_USER=admin
  #     # - VIRTUAL_HOST=test.cakecloud.info
  #     # - LETSENCRYPT_HOST=test.cakecloud.info
  #     # - LETSENCRYPT_EMAIL=cakecloudinfo@gmail.com

  #   # links:
  #   #   - db_nextcloud
  #   depends_on:
  #     - db_nextcloud
      # - traefik
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.nextcloud.rule=Host(`10.10.58.10`)
    #   - traefik.http.routers.nextcloud.entrypoints=https
    #   - traefik.http.routers.nextcloudtls.certresolver=letsEncrypt
    #   - traefik.port=80


      # - traefik.enable=true
      # - traefik.http.routers.nextcloud.rule=Host(`https://nextcloud.cool-family.keenetic.link`, `10.10.58.10`)
      # - traefik.http.routers.nextcloud.tls=true
      # - traefik.http.routers.nextcloud.tls.certresolver=lets-encrypt
      # - traefik.port=80
    # environment:
    #   - POSTGRES_HOST=db
    #   - POSTGRES_DB_FILE=/run/secrets/postgres_db
    #   - POSTGRES_USER_FILE=/run/secrets/postgres_user
    #   - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    #   - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
    #   - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      # - VIRTUAL_HOST=test.cakecloud.info
      # - LETSENCRYPT_HOST=test.cakecloud.info
      # - LETSENCRYPT_EMAIL=cakecloudinfo@gmail.com
    # secrets:
    #   - nextcloud_admin_password
    #   - nextcloud_admin_user
    #   - postgres_db
    #   - postgres_password
    #   - postgres_user

  # onlyoffice:
  #   container_name: onlyoffice
  #   networks:
  #     - nextcloud_network
  #   image: onlyoffice/documentserver:latest
  #   depends_on:
  #     # - traefik
  #     # - db_onlyoffice
  #     - nextcloud
  #   restart: unless-stopped
  #   volumes:
  #     - ./onlyoffice/data:/var/www/onlyoffice/Data
  #     # - ./proxy/certs/dhparam.pem:/var/www/onlyoffice/Data/certs/dhparam.pem
  #     # - ./proxy/certs/test.cakecloud.info/key.pem:/var/www/onlyoffice/Data/certs/onlyoffice.key
  #     # - ./proxy/certs/test.cakecloud.info/cert.pem:/var/www/onlyoffice/Data/certs/onlyoffice.crt
  #   environment:
  #     - JWT_ENABLED=true
  #     - JWT_SECRET=secret
  #   ports:
  #     - 8888:80
  #     - 4443:443
    # labels:
    #   - traefik.http.routers.onlyoffice.rule=Host(`https://onlyoffice.cool-family.keenetic.link`)
    #   - traefik.http.routers.onlyoffice.tls=true
    #   - traefik.http.routers.onlyoffice.tls.certresolver=lets-encrypt
    #   - traefik.port=443

#   plex:
#     image: lscr.io/linuxserver/plex:latest
#     restart: unless-stopped
#     # depends_on:
#       # - traefik
# #      - db_plex
#     container_name: plex
#     network_mode: host
#     environment:
#       - PUID=1000
#       - PGID=1000
#       - TZ=Europe/Moscow
#       - VERSION=docker
#       - PLEX_CLAIM=my_claim
#     volumes:
#       - /home/library/movies/library:/config
#       - /home/library/movies/shows:/tv
#       - /home/library/movies/movies:/movies
    # networks:
      # - nextcloud_network
    # labels:
    #   - traefik.http.routers.plex.rule=Host(`https://plex.cool-family.keenetic.link`)
    #   - traefik.http.routers.plex.tls=true
    #   - traefik.http.routers.plex.tls.certresolver=lets-encrypt
    #   - traefik.port=443
  
# networks:
#   nextcloud_network:
#     external: false
  # traefik_network:
  #   external: true