version: "3.9"

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - VERSION=docker
      - PLEX_CLAIM=my_claim
    volumes:
      - /home/library/movies/library:/config
      - /home/library/movies/shows:/tv
      - /home/library/movies/movies:/movies

  nextcloud_db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - secret.env

  redis:
    image: redis:alpine
    restart: always

  nextcloud_web:
    image: nextcloud:apache
    restart: always
    ports:
      - 15880:80
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud_db
      - REDIS_HOST=redis
    env_file:
      - secret.env
    depends_on:
      - nextcloud_db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - ./nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud_db
      - redis

networks:
    external:
      name: keenetic-net
