entryPoints:

  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https

  https:
    address: ":443"
    http:
      tls:
        certResolver: letsEncrypt

certificatesResolvers:
  letsEncrypt:
    acme:
      email: "razielset@gmail.com"
      storage: acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: http
api:
  dashboard: true
# middlewares:
#   my-fail2ban:
#     plugin:
#       fail2ban:
#         rules:
#           bantime: "3h"
#           findtime: "10m"
#           maxretry: 4
#           enabled: true
#           urlregexp:
#             - ""
#           urlregexp: ""
#           ports: "80:443"

#           accessLog:
#   filePath: "/var/log/traefik.log"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false