services:
  # Медиасервер для просмотра
  photoprism:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    container_name: photoprism
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "true"  
      PHOTOPRISM_DISABLE_TENSORFLOW: "true"          # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "true"               # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "true"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_ADMIN_USER: "librarian"            
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}          # initial admin password (8-72 characters)
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # MariaDB 10.5.12+ (MySQL successor) offers significantly better performance compared to SQLite
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database, see MARIADB_DATABASE in the mariadb service
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database username, must be the same as MARIADB_USER
      PHOTOPRISM_DATABASE_PASSWORD: ${MARIADB_PASSWORD}       # MariaDB database password, must be the same as MARIADB_PASSWORD
      PHOTOPRISM_FFMPEG_ENCODER: "software"          # H.264/AVC encoder (software, intel, nvidia, apple, raspberry, or vaapi)
      PHOTOPRISM_FFMPEG_BITRATE: "18"              # video bitrate limit in Mbps (default: 60)
      # Оптимизация CPU (i5-9400F)
      FFMPEG_THREADS: "6"                  # по числу ядер i5-9400F
      OMP_NUM_THREADS: "4"                 # для параллельной обработки
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - "/storage/originals:/photoprism/originals"               # Original media files (DO NOT REMOVE)
      - "/storage/import:/photoprism/import"                  # *Optional* base folder from which files can be imported to originals
      - "/storage/storage/sidecar:/photoprism/storage/sidecar"    # HDD
      - "/storage/storage/config:/photoprism/storage/config"      # HDD
      - "/home/librarian/library/media_server/photoprism/storage/cache:/photoprism/storage/cache"                  # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
      
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    security_opt: 
      - seccomp:unconfined
      - apparmor:unconfined
    command: 
      --innodb-buffer-pool-size=12G 
      --innodb-buffer-pool-instances=6
      --innodb-log-file-size=2G
      --innodb-flush-method=O_DIRECT 
      --innodb-io-capacity=2000 
      --innodb-io-capacity-max=4000
      --innodb-read-io-threads=6
      --innodb-write-io-threads=3
      --transaction-isolation=READ-COMMITTED 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci 
      --max-connections=512 
      --innodb-rollback-on-timeout=OFF 
      --innodb-lock-wait-timeout=120
    volumes:
      - "/home/librarian/library/media_server/mariadb:/var/lib/mysql" # DO NOT REMOVE
      - "/storage/mariadb_dumps:/backups" 
    environment:
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_INNODB_USE_NATIVE_AIO: "1"
      MARIADB_PERFORMANCE_SCHEMA: "ON"
      MARIADB_DEFAULT_TIME_ZONE: "+03:00"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD} 

# Torrserver для торентов
  torrserver:
    image: ghcr.io/yourok/torrserver:latest
    container_name: torrserver
    restart: unless-stopped
    ports:
      - "8090:8090"  # Веб-интерфейс и API
    volumes:
      - /home/librarian/torrserver/config:/opt/torrserver/config
      - /home/librarian/torrserver/log:/opt/torrserver/log
      - /media_data/torrent:/opt/torrserver/torrents
    environment:
      - TZ=Europe/Moscow  # Часовой пояс
      - TS_DONTKILL=true
      - TS_SEARCHWA=true
      - TS_TORR_DIR=/opt/torrserver/torrents
      - TS_PATH=/opt/torrserver/config
      - TS_LOGPATHDIR=/opt/torrserver/log
